# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadnetwork',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=25832),
        ),
    ]
